version = 1

[[annotations]]
path = ["LICENSE", "README.md"]
SPDX-FileCopyrightText = "2025 Red Hat Inc."
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["tests/ovs-netlink.pcap"]
SPDX-FileCopyrightText = "2025 Red Hat Inc."
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["debian/**"]
SPDX-FileCopyrightText = "2025 Red Hat Inc."
SPDX-License-Identifier = "GPL-2.0-or-later"
